### ISSUE TITLE
Postgres version doesn't support jsonb

### ISSUE THREAD

**Issue by milica-nerlovic** [shiroyasha/boxbox#8]
With current 9.3 version, I get an error:
```
Caused by:
PG::UndefinedObject: ERROR:  type "jsonb" does not exist
```

**Comment by nikolalsvk** [comment]
In my boxbox I'm installing 9.5 version https://github.com/nikolalsvk/boxbox

**Comment by shiroyasha** [comment]
@milica-nerlovic @nikolalsvk let's use this repository to continue development and report issues.

https://github.com/renderedtext/boxbox
